build:
	@./gradlew clean build

lint:
	@./gradlew checkstyleTest
	@./gradlew checkstyleMain

test:
	@./gradlew test

report:
	@./gradlew jacocoTestReport

clean:
	@./gradlew clean

install:
	@./gradlew clean install

.PHONY: build
